---
#UPDATE - UPGRADE
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
   
    #INSTALL i386 COMMON PACKAGES 
- name: Instala paquetes common i386  
  apt:
    name: "{{ packages }}"
    update_cache: "{{add_i386.changed}}"
  vars:
    packages:
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - libasound2-plugins:i386
      - wine-stable:i386
      - wine32-development

#INSTALL COMMON PACKAGES 
- name: Instala paquetes common
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - acl
      - apt-transport-https
      - apt-xapian-index
      - aptitude
      - arc-theme
      - arj
      - atop
      - autoconf
      - automake
      - awscli
      - balena-etcher-electron
      - bc
      - bison
      - boinc-client
      - boinc-manager
      - boinc-screensaver
      - boot-repair
      - brasero-cdrkit
      - browser-plugin-vlc
      - build-essential
      - ca-certificates
      - catfish
      - ccze
      - checkinstall
      - chromium-browser
      - chromium-browser-l10n
      - chromium-codecs-ffmpeg
      - clang
      - cmake
      - cmake-curses-gui
      - collectd
      - compiz
      - compiz-plugins-extra
      - compizconfig-settings-manager
      - curl
      - dbus
      - dconf-editor
      - dconf-tools
      - default-jdk
      - default-jre
      - dia
      - dirmngr
      - dnsmasq
      - docker
      - docker-ce
      - docker-compose
      - dropbox
      - ebtables
      - fdupes
      - figlet
      - file-roller
      - filezilla
      - filezilla-common
      - filezilla-theme-papirus
      - fonts-noto
      # - forticlient
      - fpc
      - freeglut3
      - fslint
      - g++
      - gcc
      - gdebi
      - gimp
      - gir1.2-clutter-1.0
      - gir1.2-gtop-2.0
      - gir1.2-networkmanager-1.0
      - git
      - git-flow
      - git-ftp
      - git-lfs
      - gnome-shell-extensions
      - gnome-tweak-tool
      - gnupg2
      - golang-go
      - google-cloud-sdk
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-cbt
      - google-cloud-sdk-cloud-build-local
      - google-cloud-sdk-datalab
      - google-cloud-sdk-app-engine-go
      - google-cloud-sdk-app-engine-java
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-python-extras
      - google-cloud-sdk-pubsub-emulator
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-datastore-emulator
      - google-chrome-stable
      - gpick
      - grub-customizer
      - gufw
      - hardinfo
      - hddtemp
      - htop
      - icedtea-plugin
      - iftop
      - intel-microcode
      - iotop
      - iptables-persistent
      - iptstate
      - jq
      - k3b
      - kdeconnect
      - kubectl
      - libavformat-dev
      - libdvd-pkg
      - libegl1-mesa
      - libelf-dev
      - libffi-dev
      - libfile-tee-perl
      - libfreetype6-dev
      - libgdbm-dev
      - libguestfs-perl
      - libjack-dev
      - libjack0
      - libjansson-dev
      - liblua5.3-dev
      - libmagic-dev
      - libncurses5-dev
      - libopencv-highgui-dev
      - libpython-dev
      - libportmidi-dev
      - libreadline-dev
      - libswscale-dev
      - libsdl2-image-dev
      - libsqlite3-dev
      - libssl-dev
      - libstdc++5
      - libstdc++6
      - libsvn-java
      - libtool
      - libvirt-bin
      - libvirt-dev
      - libxml-writer-perl
      - libxml2-dev
      - libxslt-dev
      - libyaml-dev
      - linux-generic
      - linux-headers-generic
      - linux-signed-generic
      - linuxbrew-wrapper
      - lldpd
      - lm-sensors
      - lsb-release
      - lshw
      - lxd
      - lxd-client
      - lutris
      - mailutils
      - make
      - meld
      - module-assistant
      - moreutils
      - mpack
      - multipath-tools
      - multitail
      - mysql-workbench
      - mysql-workbench-data
      - nano
      - ncdu
      - netcat
      - netcat-openbsd
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - nfs-common
      - nfs-kernel-server
      - nmap
      - nmon
      - nodejs
      - ntp
      - ntpdate
      - numix-blue-gtk-theme
      - numix-gtk-theme
      - numix-icon-theme
      - numix-icon-theme-circle
      - numix-icon-theme-square
      - nvidia-cuda-dev
      - nvidia-cuda-toolkit
      - openfortivpn
      - openssh-client
      - openssh-server
      - openvpn
      - p7zip-full
      - p7zip-rar
      - papirus-icon-theme
      - pepperflashplugin-nonfree
      - pgadmin3
      - pigz
      - pkg-config
      - plank
      - playonlinux
      - portaudio19-dev
      - postfix
      - powertop
      - preload
      - psensor
      - pulseaudio-equalizer
      - putty-tools
      - pv
      - python
      - python-dev
      - python-gpg
      - python-pip
      - python-setuptools
      - qemu
      - qemu-kvm
      - quodlibet
      - rar
      - rbenv
      - redshift
      - redshift-gtk
      - remmina
      - rdesktop
      - rdfind
      - rtl8812au-dkms
      - ruby-dev
      - ruby-full
      - screen
      - sharutils
      - shutter
      - siege
      - skypeforlinux
      - smartmontools
      - snapd
      - snmp
      - snmp-mibs-downloader
      - snmpd
      - software-properties-common
      - soundconverter
      - spotify-client
      - ssh-askpass
      - steam-installer
      - stress
      - sublime-merge
      - sublime-text
      - subversion
      - sudo
      - swaks
      - synaptic
      - syncthing
      - synergy
      - sysstat
      - tcpdump
      - telnetd
      - terminator
      - tinyca
      - tmux
      - tor
      - torbrowser-launcher
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - ukuu
      - unace
      - unixodbc-dev
      - unrar
      - unzip
      - uuid-runtime
      - vim
      - vim-common
      - vim-gnome
      - vim-gtk
      - vim-gui-common
      - vim-snippets
      - virt-manager
      - virt-viewer
      - virtinst
      - virtualbox-6.0
      - vlc
      - whois
      #- wine1.8
      #- wine32-development
      - xclip
      - xinetd
      - xserver-xorg
      - xserver-xorg-input-all
      - xserver-xorg-video-all
      - yarn
      - zip
      - zlib1g-dev
      - zsh
    state: present
  #register: common-packages-installation
  tags: common

- name: Install snaps
  snap:
    name:
      - k9s
      - postman
      - insomnia
      - telegram-desktop
      - discord
      - keepassxc

- name: Install snaps classic
  snap:
    name:
      - slack
      # - sublime-text
      - eclipse
      - atom
      - phpstorm
      - code
      # - skype
    classic: yes
