---
- name: apt-get clean
  shell: apt-get clean
  become: true
  become_user: root

- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
  ignore_errors: true

#ADD REPOS
- name: Add Repo Numix
  apt_repository:
    repo: ppa:numix/ppa
    codename: '{{ codename }}'
    update_cache: no

- name: Add Repo Git Core
  apt_repository:
    repo: ppa:git-core/ppa
    codename: '{{ codename }}'
    update_cache: no

- name: Add Repo Papirus
  apt_repository:
    repo: ppa:papirus/papirus
    codename: '{{ codename }}'
    update_cache: no

- name: Add Repo webupd8 general porpuses
  apt_repository:
    repo: ppa:nilarimogard/webupd8
    codename: '{{ codename }}'
    update_cache: no
  when: codename != "jammy" or codename != "vanessa"

#Google Chrome
# - apt_key:
#     url: https://dl.google.com/linux/linux_signing_key.pub
#     state: present

    # - apt_repository:
    #     repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    #     state: present
    #     filename: google-chrome
    #     update_cache: no

#SyncThing
- apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
- apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    update_cache: no

#Spotify
- apt_key:
    # keyserver: hkp://keyserver.ubuntu.com:80
    # id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
- apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    update_cache: no

#GRUB CUSTOMIZER
- apt_repository:
    repo: ppa:danielrichter2007/grub-customizer
    codename: '{{ codename }}'
    update_cache: no

# ETCHER
- apt_key:
    url: https://dl.cloudsmith.io/public/balena/etcher/gpg.70528471AFF9A051.key
    # keyserver: hkps://keyserver.ubuntu.com:443
    # id: 379CE192D401AB61
    state: present
- apt_repository:
    repo: 'deb https://dl.cloudsmith.io/public/balena/etcher/deb/ubuntu  {{ codename }} main'
    # repo: deb https://deb.etcher.io stable etcher
    state : present
    update_cache: no

# DROPBOX
# - apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
 #    state: present
 # - apt_repository:
 #     repo: 'deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu disco main'
 #     state : present
 #     update_cache: no

# BOOT REPAIR
- apt_repository:
    repo: ppa:yannubuntu/boot-repair
    codename: '{{ codename }}'
    update_cache: no

# SHUTTER
## Disable for deprecation repo notice: https://www.linuxuprising.com/2021/08/official-shutter-screenshot-tool.html
- apt_repository:
    repo: ppa:linuxuprising/shutter  
    codename: '{{ codename }}'
    state : absent
    update_cache: no
  when: codename != "jammy" or codename != "vanessa"
- apt_repository:
    repo: ppa:shutter/ppa 
    codename: '{{ codename }}'
    state : present
    update_cache: no
  when: codename != "jammy" or codename != "vanessa"

# WINE
- apt_key:
    # keyserver: hkp://keyserver.ubuntu.com:80
    # id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present
- apt_repository:
    repo: 'deb https://dl.winehq.org/wine-builds/ubuntu/ {{ codename }} main'
    state: present
    update_cache: no

#vlc-plugin-bittorrent
- apt_repository:
    repo: ppa:linuxuprising/apps
    codename: '{{ codename }}'
    update_cache: no
  when: codename != "jammy" or codename != "vanessa"

# Lutris
- apt_repository:
    repo: ppa:lutris-team/lutris
    codename: '{{ codename }}'
    update_cache: no
    
# Lutris Vulkan Drivers
## Nvidia PPA
- apt_repository:
    repo: ppa:graphics-drivers/ppa
    codename: '{{ codename }}'
    update_cache: no

## System-76 Drivers
- apt_repository:
    repo: ppa:system76-dev/stable
    codename: '{{ codename }}'
    update_cache: no
  state: absent

# Lutris-Retroarch compatible library
- apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
    codename: '{{ codename }}'
    state : present
    update_cache: no

# Wallpaper changers
- apt_repository:
    repo: ppa:sicklylife/shotwell
    codename: '{{ codename }}'
    update_cache: no
  when: codename != "jammy" or codename != "vanessa"

- apt_repository:
    repo: ppa:peterlevi/ppa
    codename: '{{ codename }}'
    update_cache: no

#Audio-Recorder
- apt_repository:
    repo: ppa:audio-recorder/ppa
    codename: '{{ codename }}'
    update_cache: no


# Astronomy
# ## Celestia
# - apt_key:
#     url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
#     state: present

# - apt_repository:
#     repo: 'deb [trusted=yes] https://dl.bintray.com/celestia/releases-deb bionic universe'
#     state : present
#     filename: celestia-bintray
#     # register: apt_result
#     # until: apt_result|success
#     update_cache: no
#     # cache_valid_time: 3600
#     # retries: 10
#     # delay: 1
#     # ignore_errors: true

# Timekpr
# - apt_repository:
    # repo: ppa:mjasnik/ppa
    # codename: '{{ codename }}'
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1C27A13ABDE62E7917743810AF91A06147FA1307
    state: present
- apt_repository:
    repo: 'deb http://ppa.launchpad.net/mjasnik/ppa/ubuntu {{ codename }} main'
    state : present
    update_cache: no

# Signal
- apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    # keyserver: hkps://keyserver.ubuntu.com:443
    # id: 379CE192D401AB61
    state: present
- apt_repository:
    repo: 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main'
    state : present
    update_cache: no

- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
  ignore_errors: true
