---
    #ADD REPOS
    - apt_repository:
        repo: ppa:numix/ppa
        codename: focal

    - apt_repository:
        repo: ppa:system76/pop
        codename: focal

#    - apt_repository:
#        repo: ppa:system76-dev/stable

    - apt_repository:
        repo: ppa:git-core/ppa
        codename: focal

    - apt_repository:
        repo: ppa:papirus/papirus
        codename: focal

    - apt_repository:
        repo: ppa:nilarimogard/webupd8
        codename: focal

    #Google Chrome
    - apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    # #Sublime Text & Sublime Merge
    # - apt_key:
    #     url: https://download.sublimetext.com/sublimehq-pub.gpg
    #     state: present

    # - apt_repository:
    #     repo: 'deb https://download.sublimetext.com/ apt/stable/'
    #     state: present

    #SyncThing
    - apt_key:
        url: https://syncthing.net/release-key.txt
        state: present

    - apt_repository:
        repo: 'deb https://apt.syncthing.net/ syncthing stable'
        state: present

    #Spotify
    - apt_key:
        # keyserver: hkp://keyserver.ubuntu.com:80
        # id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        url: https://download.spotify.com/debian/pubkey.gpg
        state: present

    - apt_repository:
        repo: 'deb http://repository.spotify.com stable non-free'
        state: present

    # #Virtualbox
    # - apt_key:
    #     url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    #     state: present

    # - apt_key:
    #     url: https://www.virtualbox.org/download/oracle_vbox.asc
    #     state: present

    # - apt_repository:
    #     repo: 'deb https://download.virtualbox.org/virtualbox/debian focal contrib'
    #     state: present

    # #Docker
    # - apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
       
    # # - apt_repository:
    # #       repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    # #       state : present
    # #   when: ansible_distribution == 'Linux Mint'

    # - apt_repository:
    #       repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    #       state : present
    #   when: ansible_distribution == 'Ubuntu'

    # #GCLOUD SDK
    # - apt_key:
    #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    #     state: present
       
    # # - apt_repository:
    # #       repo: 'deb http://packages.cloud.google.com/apt cloud-sdk-focal main'
    # #       state : present
    # #   when: ansible_distribution == 'Linux Mint'

    # - apt_repository:
    #       repo: 'deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main'
    #       state : present
    #   when: ansible_distribution == 'Ubuntu'

    #GRUB CUSTOMIZER
    - apt_repository:
        repo: ppa:danielrichter2007/grub-customizer
        codename: disco

    #ETCHER
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: 379CE192D401AB61
        state: present

    - apt_repository:
          repo: 'deb https://deb.etcher.io stable etcher'
          state : present

    # DROPBOX
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
        state: present

    - apt_repository:
          repo: 'deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu disco main'
          state : present

    #BOOT REPAIR
    - apt_repository:
        repo: ppa:yannubuntu/boot-repair

    #SHUTTER
    - apt_repository:
        repo: ppa:linuxuprising/shutter  

    #WINE
    - apt_key:
        # keyserver: hkp://keyserver.ubuntu.com:80
        # id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        url: https://dl.winehq.org/wine-builds/winehq.key
        state: present

    - apt_repository:
        repo: 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
        state: present

    #LUTRIS
    - apt_repository:
        repo: ppa:lutris-team/lutris
